from distutils.core import setup
setup(
  name='EnvConfigurator',
  packages=['EnvConfigurator'],
  version='0.2',
  license='MIT',
  description='Load and Parse Environment Variable(s) with just 3 lines of code.',
  author='Muhammad Zaid Afzal',
  author_email='zaidafzal@protonmail.com',
  url='https://github.com/z4id',
  download_url='https://github.com/z4id/EnvConfigurator/archive/refs/tags/v_01.tar.gz',
  keywords=['ENVIRONMENT', 'CONFIGURATION', 'VARIABLE'],
  classifiers=[
    'Development Status :: 3 - Alpha',
    'Intended Audience :: Developers',
    'Topic :: Software Development :: Build Tools',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.4',
    'Programming Language :: Python :: 3.5',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
  ],
)
